buildscript {
    repositories {
        maven { url 'https://maven.aliyun.com/repository/public/' }
        maven { url "https://www.jetbrains.com/intellij-repository/releases/" }
        maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
        mavenLocal()
        mavenCentral()
        gradlePluginPortal()
    }
    dependencies {

    }
}

plugins {
    id 'java'
    id 'idea'
    id 'org.jetbrains.intellij' version '1.17.4'
}

//2.1 插件配置
// apply plugin: 'org.jetbrains.intellij'
// apply plugin: 'idea'
// apply plugin: 'java'


group 'com.liyi'
version '2.2.0'

sourceCompatibility = JavaVersion.VERSION_1_8
targetCompatibility = JavaVersion.VERSION_1_8

repositories {
    maven { url 'https://maven.aliyun.com/repository/public/' }
    maven { url "https://www.jetbrains.com/intellij-repository/releases" }
}

dependencies {
//     testCompile group: 'junit', name: 'junit', version: '4.12'
    /*compile group: 'com.alibaba', name: 'druid', version: '1.1.23'*/
//     compile fileTree(dir: 'libs', include: [ '*'])
}

intellij {
    pluginName = "Li-MybatisLog"
    version = "2023.3.8"
    type = "IC"
    sandboxDir = "${rootProject.rootDir}/idea-sandbox"
    updateSinceUntilBuild = false
    downloadSources = false
}

processResources {
    from('src/main/java') {
        include '**/*.png'
    }
}

patchPluginXml {

}

tasks.withType(JavaCompile) {
    options.encoding = "UTF-8"
}